### ISSUE TITLE
[Bug] [UI] The icon show incorrect when database test connect failed.

### ISSUE THREAD

**Issue by QuakeWang** [datavane/datavines#157]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When configuring the connect of MySQL database, it shows `Test Connect Failed`, but the icon is green with a right sign. In fact, it should be an error icon.

BTW, it can work finely, just a UI error.

### DataVines Version

dev

### DataVines Config

```conf
default
```

### Running Command

```shell
In Web UI, click the `Test Connect` button.
```

### Error Exception

```log
[ERROR] 2023-06-27 10:56:34.240 io.datavines.connector.plugin.JdbcConnector:[193] - java.sql.SQLException: Access denied for user 'root'@'10.xxx.xx.19' (using password: YES)
java.sql.SQLException: Access denied for user 'root'@'10.xxx.xx.19' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at io.datavines.connector.plugin.JdbcConnector.testConnect(JdbcConnector.java:185)
```

### Engine Type

local

### Java Version

JDK 1.8

### Screenshots

![connect-failed](https://github.com/datavane/datavines/assets/45645138/0a031d65-0292-4aa2-b7ae-d1ef3a8cdf20)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The problem has been fixed.
