### ISSUE TITLE
[Bug] 无法将jdk1.8升级到11，只能用jdk1.8才行，一升级，就挂

### ISSUE THREAD

**Issue by kafeihouye** [datavane/datavines#191]
Caused by: javax.servlet.ServletException: jsp==org.apache.jasper.servlet.JspServlet@19c47{jsp=null,order=3,inst=true,async=true,src=EMBEDDED:null,STARTED}
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650)
at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
at org.eclipse.jetty.servlet.ServletHandler.lambdainitialize0(ServletHandler.java:731)
at java.base/java.util.stream.SortedOpsSizedRefSortingSink.end(SortedOps.java:357)atjava.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)atjava.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)atjava.base/java.util.stream.StreamSpliteratorsWrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
at java.base/java.util.stream.StreamsConcatSpliterator.forEachRemaining(Streams.java:735)atjava.base/java.util.stream.ReferencePipelineHead.forEach(ReferencePipeline.java:658)
at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContextJettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)atorg.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)atorg.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:220)atorg.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:156)...16moreCausedby:java.lang.ClassCastException:classjdk.internal.loader.ClassLoadersAppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
at org.apache.jasper.compiler.JspRuntimeContext.(JspRuntimeContext.java:174)
at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
... 29 more
[INFO] 2023-08-16 17:53:07.713 io.datavines.server.DataVinesServer:[117] - server is stopping ..., cause : shutdownHook

**Comment by lixuey** [comment]
I will fix it

**Comment by zixi0825** [comment]
The problem has been fixed.
