### ISSUE TITLE
[issue] quality metric job always fails

### ISSUE THREAD

**Issue by jiujiucandy** [datavane/datavines#223]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

**when i run a quality metric job, it is always fails and the logs show that the drop permission on the table is not displayed,but the current user has the drop permission。where was the table " invalidate_items_xxxx " created?**

### DataVines Version

dev

### DataVines Config

```conf
Perform quality check tasks according to the guide
```

### Running Command

```shell
Perform quality check tasks according to the guide
```

### Error Exception

```log
[INFO] 2023-09-14 09:06:30.059 [JobExecutionUniqueId=JOB-20230914-client_local_7:[90] - transform sql is: select * from xxxxx.dv_catalog_entity_instance where (properties is null ), transform_type is : invalidate_items
[ERROR] 2023-09-14 09:06:30.063 [JobExecutionUniqueId=JOB-20230914-client_local_7:[112] - transform execute error:
java.sql.SQLException: statement is closed
at com.alibaba.druid.pool.DruidPooledStatement.checkOpen(DruidPooledStatement.java:174)
at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:616)
at io.datavines.engine.local.transform.sql.InvalidateItemsExecutor.execute(InvalidateItemsExecutor.java:40)
at io.datavines.engine.local.transform.sql.SqlTransform.process(SqlTransform.java:93)
at io.datavines.engine.local.api.LocalExecution.lambda$execute$0(LocalExecution.java:113)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at io.datavines.engine.local.api.LocalExecution.execute(LocalExecution.java:107)
at io.datavines.engine.core.BaseDataVinesBootstrap.parseConfigAndExecute(BaseDataVinesBootstrap.java:79)
at io.datavines.engine.core.BaseDataVinesBootstrap.execute(BaseDataVinesBootstrap.java:43)
at io.datavines.engine.local.executor.LocalEngineExecutor.execute(LocalEngineExecutor.java:44)
at io.datavines.server.dqc.executor.runner.JobRunner.run(JobRunner.java:69)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLSyntaxErrorException: DROP command denied to user 'xxxx for table 'invalidate_items_4f57b3ec'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:622)
at io.datavines.engine.local.api.utils.SqlUtils.dropView(SqlUtils.java:266)
at io.datavines.engine.local.transform.sql.InvalidateItemsExecutor.execute(InvalidateItemsExecutor.java:39)
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
The xxxx user need permission to create and delete view.
