### ISSUE TITLE
[Bug] [engine] postgresql source tale is not exist for rules and data profiling while sql editor works

### ISSUE THREAD

**Issue by wzcyc** [datavane/datavines#264]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

连接postgresql后，可以正常获取表目录，在SQL编辑器正常可以执行。但是运行数据概览和规则作业报错。source table is not exist

### DataVines Version

latest

### DataVines Config

```conf
no additional
```

### Running Command

```shell
any
```

### Error Exception

```log
[ERROR] 2023-11-01 17:28:30.609 [JobExecutionUniqueId=JOB-20231101-client_local_5:[160] - execute error
io.datavines.common.exception.DataVinesException: source table is not exist
at io.datavines.engine.local.api.LocalExecution.execute(LocalExecution.java:74)
at io.datavines.engine.core.BaseDataVinesBootstrap.parseConfigAndExecute(BaseDataVinesBootstrap.java:79)
at io.datavines.engine.core.BaseDataVinesBootstrap.execute(BaseDataVinesBootstrap.java:43)
at io.datavines.engine.local.executor.LocalEngineExecutor.execute(LocalEngineExecutor.java:44)
at io.datavines.server.dqc.executor.runner.JobRunner.run(JobRunner.java:69)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### Engine Type

local

### Java Version

1.8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
This bug has been fixed.

**Comment by wzcyc** [comment]
今天下了新代码，发现问题还在。 

只做简单的行数统计，发现有两个DB。访问了DB.DB.table

,\"transforms\":[{\"plugin\":\"sql\",\"type\":\"actual_value\",\"config\":{\"index\":0,\"output_table\":\"invalidate_count_d2af48bc\",\"sql\":\"select count(1) as actual_value_d2af48bc from scorecard.scorecard.t_sc_feature_score_card\"}},

用聚合SQL，也是如此处理。

"transforms\":[{\"plugin\":\"sql\",\"type\":\"actual_value\",\"config\":{\"index\":0,\"output_table\":\"invalidate_count_d10155ef\",\"sql\":\"select count(1) as actual_value_d10155ef from scorecard.scorecard.t_sc_feature_score_card\"}},
