### ISSUE TITLE
trino连接器无密码但是需要ssl认证

### ISSUE THREAD

**Issue by codeBoy777** [datavane/datavines#297]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

使用trino连接跑local任务报错，显示需要ssl认证
![image](https://github.com/datavane/datavines/assets/50009087/cf5b769c-73cc-48e7-aec2-2a464484fdbc)

### DataVines Version

dev

### DataVines Config

```conf
{
    "name": "trino_test_1701336709282",
    "executePlatformType": "client",
    "executePlatformParameter": {},
    "engineType": "local",
    "engineParameter": {},
    "parameter": {
        "connectorParameter": {
            "type": "trino",
            "parameters": {
                "port": "28080",
                "catalog": "hive",
                "host": "121.41.122.195",
                "user": "root"
            }
        },
        "metricParameterList": [
            {
                "metricType": "table_row_count",
                "metricParameter": {
                    "database": "biz",
                    "table": "hlj_db__bd__customer_base_info"
                },
                "expectedType": "table_total_rows",
                "resultFormula": "count",
                "operator": "eq",
                "threshold": 100
            }
        ]
    },
    "errorDataStorageType": "",
    "errorDataStorageParameter": {},
    "validateResultDataStorageType": "mysql",
    "validateResultDataStorageParameter": {
        "password": "******",
        "driver": "com.mysql.cj.jdbc.Driver",
        "user": "root",
        "url": "jdbc:mysql://172.30.10.90:3306/datavines?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai"
    },
    "retryTimes": 0,
    "retryInterval": 1000,
    "timeout": 3600,
    "timeoutStrategy": "WARN",
    "languageEn": false
}
```

### Running Command

```shell
平台内运行
```

### Error Exception

```log
io.datavines.common.exception.DataVinesException: java.sql.SQLException: Authentication using username/password requires SSL to be enabled
at io.datavines.common.utils.ConnectionUtils.getConnection(ConnectionUtils.java:68)
at io.datavines.common.utils.ConnectionUtils.getConnection(ConnectionUtils.java:47)
at io.datavines.engine.local.api.entity.ConnectionHolder.getConnection(ConnectionHolder.java:46)
at io.datavines.engine.local.connector.BaseJdbcSource.checkTableExist(BaseJdbcSource.java:106)
at io.datavines.engine.local.api.LocalExecution.execute(LocalExecution.java:73)
at io.datavines.engine.core.BaseDataVinesBootstrap.parseConfigAndExecute(BaseDataVinesBootstrap.java:84)
at io.datavines.engine.core.BaseDataVinesBootstrap.execute(BaseDataVinesBootstrap.java:48)
at io.datavines.engine.local.executor.LocalEngineExecutor.execute(LocalEngineExecutor.java:44)
at io.datavines.server.dqc.executor.runner.JobRunner.run(JobRunner.java:66)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### Engine Type

local

### Java Version

8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by codeBoy777** [comment]
看下这个，trino无密码需要ssl认证，并且也有同学反应没有得到解决

**Comment by zixi0825** [comment]
> 看下这个，trino无密码需要ssl认证，并且也有同学反应没有得到解决

这是两个问题，另外一个issue的是有SSL认证导致的，这个问题明天会提交代码修复

**Comment by zixi0825** [comment]
问题已经修复
