### ISSUE TITLE
[Bug] [Error Data Storage] Sink error data error when column datatype is 'tinyint(1)'

### ISSUE THREAD

**Issue by AlexChen68** [datavane/datavines#358]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

当使用错误数据源存储错误数据时，由于源表中存在一个类型为 `tinyint(1)` 的字段，在 `ErrorDataSinkExecutor` 的 `sinkErrorData()` 查询出来的错误结果列表中，该字段的值为 `true`，而不是 `1`，从而导致 `sink error data error`。

<img width="1026" alt="截屏2024-02-08 20 37 35" src="https://github.com/datavane/datavines/assets/46132215/d97f441a-74a7-4e20-96d6-2f172291f1d6">
<img width="1728" alt="截屏2024-02-08 20 36 21" src="https://github.com/datavane/datavines/assets/46132215/ec4aef62-b001-4bc6-8434-2f257b7ebe9f">

### DataVines Version

1.0.0-SNAPSHOT

### DataVines Config

```conf
无
```

### Running Command

```shell
本地源码启动，使用 mysql 数据源
```

### Error Exception

```log
[INFO] 2024-02-08 20:34:57.551 [JobExecutionUniqueId=JOB-20240208-client_local_2:[329] - create error data table : CREATE TABLE IF NOT EXISTS column_null_perm_1707395677249 (id BIGINT,parent_id BIGINT,tree_path TEXT,name TEXT,type TINYINT,path TEXT,component TEXT,perm TEXT,visible TINYINT,sort BIGINT,icon TEXT,redirect TEXT,create_time TEXT,update_time TEXT,always_show TINYINT,keep_alive TINYINT)
[ERROR] 2024-02-08 20:36:45.719 [JobExecutionUniqueId=JOB-20240208-client_local_2:[293] - sink error data error :
java.lang.NumberFormatException: For input string: "true"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:580)
at java.lang.Byte.parseByte(Byte.java:149)
at java.lang.Byte.parseByte(Byte.java:175)
at io.datavines.engine.local.connector.executor.ErrorDataSinkExecutor.sinkErrorData(ErrorDataSinkExecutor.java:201)
at io.datavines.engine.local.connector.executor.ErrorDataSinkExecutor.execute(ErrorDataSinkExecutor.java:71)
at io.datavines.engine.local.connector.BaseJdbcSink.output(BaseJdbcSink.java:98)
at io.datavines.engine.local.api.LocalExecution.execute(LocalExecution.java:146)
at io.datavines.engine.core.BaseDataVinesBootstrap.parseConfigAndExecute(BaseDataVinesBootstrap.java:79)
at io.datavines.engine.core.BaseDataVinesBootstrap.execute(BaseDataVinesBootstrap.java:43)
at io.datavines.engine.local.executor.LocalEngineExecutor.execute(LocalEngineExecutor.java:44)
at io.datavines.server.dqc.executor.runner.JobRunner.run(JobRunner.java:66)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
at java.util.concurrent.FutureTask.run(FutureTask.java)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
```

### Engine Type

local

### Java Version

Java 8

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xxzuo** [comment]
考虑在 jdbc 连接 添加一个 `tinyInt1isBit=false` 再试一下
 参考 https://dev.mysql.com/doc/connectors/en/connector-j-reference-type-conversions.html

**Comment by AlexChen68** [comment]
在新建数据源的参数中添加确实有效，感谢！
