### ISSUE TITLE
paimon表的列失败

### ISSUE THREAD

**Issue by cs3163077** [datavane/datavines#382]
### Search before asking

- [X] I had searched in the [feature](https://github.com/datavines-ops/datavines/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

环境hive+paimon。
只能获取表信息不能加载列
![image](https://github.com/datavane/datavines/assets/13974148/92455526-2e15-4460-996c-870468c05d7c)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zixi0825** [comment]
请提供一下服务的日志文件

**Comment by cs3163077** [comment]
[ERROR] 2024-03-15 17:25:45.411 io.datavines.connector.plugin.JdbcConnector:[249] - get column error, param is null.fine_output_sms :
org.apache.hive.service.cli.HiveSQLException: MetaException(message:java.lang.UnsupportedOperationException: Storage schema reading not supported)
        at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:264)
        at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:255)
        at org.apache.hive.jdbc.HiveDatabaseMetaData.getColumns(HiveDatabaseMetaData.java:225)
        at com.zaxxer.hikari.pool.ProxyDatabaseMetaData.getColumns(ProxyDatabaseMetaData.java:108)
        at com.zaxxer.hikari.pool.HikariProxyDatabaseMetaData.getColumns(HikariProxyDatabaseMetaData.java)
        at io.datavines.connector.plugin.HiveConnector.getMetadataColumns(HiveConnector.java:40)
        at io.datavines.connector.plugin.JdbcConnector.getColumns(JdbcConnector.java:238)
        at io.datavines.connector.plugin.JdbcConnector.getColumns(JdbcConnector.java:179)
        at io.datavines.server.catalog.metadata.task.CatalogMetaDataFetchExecutorImpl.executeFetchTable(CatalogMetaDataFetchExecutorImpl.java:484)
        at io.datavines.server.catalog.metadata.task.CatalogMetaDataFetchExecutorImpl.lambda$executeFetchDatabase$6(CatalogMetaDataFetchExecutorImpl.java:443)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at io.datavines.server.catalog.metadata.task.CatalogMetaDataFetchExecutorImpl.executeFetchDatabase(CatalogMetaDataFetchExecutorImpl.java:441)
        at io.datavines.server.catalog.metadata.task.CatalogMetaDataFetchExecutorImpl.lambda$executeFetchDataSource$1(CatalogMetaDataFetchExecutorImpl.java:229)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at io.datavines.server.catalog.metadata.task.CatalogMetaDataFetchExecutorImpl.executeFetchDataSource(CatalogMetaDataFetchExecutorImpl.java:228)
        at io.datavines.server.catalog.metadata.task.CatalogMetaDataFetchExecutorImpl.execute(CatalogMetaDataFetchExecutorImpl.java:92)
        at io.datavines.server.catalog.metadata.CatalogMetaDataFetchTaskRunner.run(CatalogMetaDataFetchTaskRunner.java:43)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.hive.service.cli.HiveSQLException: MetaException(message:java.lang.UnsupportedOperationException: Storage schema reading not supported)
        at org.apache.hive.service.cli.operation.GetColumnsOperation.runInternal(GetColumnsOperation.java:213)
        at org.apache.hive.service.cli.operation.Operation.run(Operation.java:247)
        at org.apache.hive.service.cli.session.HiveSessionImpl.getColumns(HiveSessionImpl.java:695)
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78)
        at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36)
        at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
        at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59)
        at com.sun.proxy.$Proxy37.getColumns(Unknown Source)
        at org.apache.hive.service.cli.CLIService.getColumns(CLIService.java:387)
        at org.apache.hive.service.cli.thrift.ThriftCLIService.GetColumns(ThriftCLIService.java:654)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetColumns.getResult(TCLIService.java:1677)
        at org.apache.hive.service.rpc.thrift.TCLIService$Processor$GetColumns.getResult(TCLIService.java:1662)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
        at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:56)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.UnsupportedOperationException: Storage schema reading not supported
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_schema_with_environment_context_result$get_schema_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:52686)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_schema_with_environment_context_result$get_schema_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:52653)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_schema_with_environment_context_result.read(ThriftHiveMetastore.java:52579)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_schema_with_environment_context(ThriftHiveMetastore.java:1491)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_schema_with_environment_context(ThriftHiveMetastore.java:1476)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getSchema(HiveMetaStoreClient.java:2015)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getSchema(HiveMetaStoreClient.java:2002)
        at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.getSchema(SessionHiveMetaStoreClient.java:334)
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:212)
        at com.sun.proxy.$Proxy30.getSchema(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient$SynchronizedHandler.invoke(HiveMetaStoreClient.java:2773)
        at com.sun.proxy.$Proxy30.getSchema(Unknown Source)
        at org.apache.hive.service.cli.operation.GetColumnsOperation.runInternal(GetColumnsOperation.java:169)
        ... 24 common frames omitted
